name: C++ Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake curl libcurl4-openssl-dev

      - name: CMake Version
        run: |
          cmake --version

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Release -S. -B build

      - name: Build
        run: cmake --build build --config Release -- -j 12
      
      - name: Run Test
        run: cd build && ctest -j14 -C Release -T test --output-on-failure
